### ISSUE TITLE
error in Jupyter notebook

### ISSUE THREAD

**Issue by ltalirz** [pyiron/pyiron_meltingpoint#14]
Hi, I wanted to use this repository as an example of reproducible science in a talk but I realized that some instructions in the `script.ipynb` jupyter notebook are broken:
![image](https://user-images.githubusercontent.com/1053245/141363912-b7e9cc85-f029-4fff-b5f3-7cd66b03e2a9.png)

By the way, I wasn't able to find a link to the repository from the corresponding [publication](https://pyiron.org/publications/2021/02/01/melting.html) - am I overlooking something?

Is there another publication where you link directly to the corresponding git repository?

**Comment by jan-janssen** [comment]
Hi @ltalirz  I am sorry I missed your issue. Which version of numpy are you using? We had an issue with numpy compatibility. But with the recent changes I made today should be compatible to the latest pyiron version as well.

**Comment by ltalirz** [comment]
Hi @jan-janssen , thanks for following up - I don't remember the numpy version but think I saw the same issue on mybinder.org

**Comment by jan-janssen** [comment]
Mybinder is using the same environment. I was able to reproduce the issue and it is fixed now by fixing the numpy version to 1.19.5.
