### ISSUE TITLE
Problem in convergence

### ISSUE THREAD

**Issue by sandeepshukla1112** [pyiron/pyiron_meltingpoint#23]
Hi, 

I am calculating the melting temperature of aluminum with ML-IAP SNAP using pyiron. In my calculations, melting temperature oscillates around the experimental value. The magnitude of the oscillations is approximately 100 K. I wonder if there may be an issue with the following pyiron parameters: 
    ```'points': 21,
    'boundary_value': 0.25,
    'ratio_boundary': 0.25,
    'fit_range_lst': [0.05, 0.01, 0.01]```.

Please let me know the meaning of these input parameters in pyiron code. 

Thanks.

**Comment by jan-janssen** [comment]
Hi @sandeepshukla1112 , 

Interatomic potentials including machine learning interatomic potentials like SNAP can only be as good as the reference / training data they are fitted to. So the ~100K difference to experiment could be related to your choice of DFT functional and material system. In terms of the parameter you quote, those sound reasonable to me, but without more details about your material system and the specific machine learning potential you use it is hard to make an absolute statement. 

Best, 

Jan
